#!/usr/bin/env node

var child = require('child_process')
  , spawn = child.spawn
  , exec = child.exec;

// CLI setup.
var program = require('commander')
  .version(require('./package').version)
  .usage('<command> [options] [nodemon-options]')
  .description('Continuously run a script against an expected output file.')
  .option('-i, --input <file>', 'sample input file')
  .option('-o, --output <file>', 'sample output file')
  .option('--nodemon-help', 'show nodemon help')
  .option('--nodemon-version', 'show nodemon version');

if(program.nodemonHelp){
  return exec('node node_modules/nodemon/ --help', function(err, stdout){
    if(err){
      console.error(err);
    }
    return process.stdout.write(stdout.toString());
  });
}

if(program.nodemonVersion){
  return exec('node node_modules/nodemon/ --version', function(err, stdout){
    if(err){
      console.error(err);
    }
    return process.stdout.write(stdout.toString());
  });
}

// Do nothing with unknown options -- capture for nodemon.
program.unknownOption = function(){};

// See hack @ https://github.com/nitoyon/livereloadx/commit/521581279a1f1d840685d49729d6d0cf3a64d1b
program._name = 'salviati';
var parsed = program.parseOptions(program.normalize(process.argv.slice(2)));
program.args = parsed.args;
if (parsed.unknown.length > 0) {
  program.parseArgs([], parsed.unknown);
}
var nodemon_flags = parsed.unknown;

if(program.args.length < 1){
  var missing_args = ['<command>'].slice(program.args.length);
  return console.error(
    '\n' +
    'error: ' + missing_args.join(', ') +
    ' argument' + (missing_args.length > 1 ? 's' : '') + ' missing' +
    '\n'
  );
}

console.log(
  ['node', 'node_modules/nodemon']
    .concat(nodemon_flags)
    .concat(['--exec'])
    .concat(program.args)
    .concat([program.input]));

// Monitor setup.
var nodemon = spawn('/usr/bin/env',
  ['node', 'node_modules/nodemon']
    .concat(nodemon_flags)
    .concat(['--exec'])
    .concat(program.args)
    .concat([program.input]),
  {
    stdio: 'inherit'
});

nodemon.on('error', function(err){
  console.error('Error:', err);
});
nodemon.on('exit', function(code){
  console.log('Exited with code', code);
});
